version: "3"
services:
  web:
    build: apache
    ports:
       - 80:80
       - 443:443
    volumes:
       - ./apache/prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf
       - ./prestashop:/app/prestashop       
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: presta
      MYSQL_USER: prestauser
      MYSQL_PASSWORD: prestapw
    volumes:
       - basedatos:/var/lib/mysql
volumes:
  basedatos: